-- PKM §5.A — the generated ABI appendix, constants half: the syscall
-- numbers, the ioctl encodings, and every constant table the header
-- groups.
--
-- The appendix is generated by compiling a probe against
-- `pkm/uapi/pkm/lcs.h`, so nothing here re-reads the header: each
-- published number is used as a program would use it and the kernel is
-- shown to agree. An ioctl number is testable because the encoding
-- carries the direction and the argument size, and a wrong one is
-- ENOTTY rather than a misread; an access right because it gates
-- exactly its own operation; a value type because a code outside the
-- table is EINVAL; an RSI status because it maps to one documented
-- errno; a watch filter bit because it selects exactly its own event
-- types.
--
-- The structure layouts of the same appendix are in abi-structs, the
-- tracepoint vocabularies in abi-tracepoints, and the prose appendix
-- §5.B in abi-notes.

local sys = require("helpers.sys")
local lcs = require("helpers.lcs")
local access = require("helpers.access")

local vm = provium:vm("v", "kernel-only"):boot()

local MACHINE_ROOT = lcs.guid()
local O_NONBLOCK = 0x800

--- A Machine source with a test key, a symlink to it and a second key.
local function machine(seed)
    local src = lcs.source(vm, { hives = {
        { name = "Machine", root = MACHINE_ROOT } } })
    src:key("Machine\\Software\\Test")
    if seed then seed(src) end
    assert(src:register())
    src:pump()
    return src
end

local function open(t, src, w, path, access_mask, flags)
    local r = lcs.open_key(src, w, -1, path, access_mask or lcs.KEY_ALL_ACCESS,
        flags)
    t:assert(r.ret >= 0, "open " .. path .. ": " .. sys.errname(r.errno or 0))
    return r.ret
end

--- An ioctl issued by its published encoded number, with an argument
--- buffer of the size that number declares, under the source pump.
local function raw_ioctl(src, w, fd, encoded, size, bytes)
    local spec = { args = { fd, encoded, 0 } }
    if size > 0 then
        spec.bufs = { bytes or string.rep("\255", size) }
        spec.ptrs = { 2 }
    end
    if src then
        return src:run(function() return w:syscall_async(sys.NR.ioctl, spec) end)
    end
    return w:syscall(sys.NR.ioctl, spec)
end

--- The size field of an encoded ioctl number.
local function ioc_size(encoded) return (encoded >> 16) & 0x3FFF end

--- Every ioctl §5.A publishes, by fd type, with the encoded number the
--- appendix gives.
local KEY_IOCTLS = {
    { "REG_IOC_QUERY_VALUE", 0xC0405200 },
    { "REG_IOC_SET_VALUE", 0x40405201 },
    { "REG_IOC_DELETE_VALUE", 0x40285202 },
    { "REG_IOC_BLANKET_TOMBSTONE", 0x40185203 },
    { "REG_IOC_QUERY_VALUES_BATCH", 0xC0185204 },
    { "REG_IOC_ENUM_VALUES", 0xC0285205 },
    { "REG_IOC_ENUM_SUBKEYS", 0xC0285206 },
    { "REG_IOC_QUERY_KEY_INFO", 0xC0405207 },
    { "REG_IOC_DELETE_KEY", 0x40185208 },
    { "REG_IOC_HIDE_KEY", 0x40185209 },
    { "REG_IOC_GET_SECURITY", 0xC010520A },
    { "REG_IOC_SET_SECURITY", 0x4018520B },
    { "REG_IOC_NOTIFY", 0x4008520C },
    { "REG_IOC_FLUSH", 0x0000520D },
    { "REG_IOC_BACKUP", 0x4004520E },
    { "REG_IOC_RESTORE", 0x4004520F },
}
local TXN_IOCTLS = {
    { "REG_IOC_COMMIT", 0x00005210 },
    { "REG_IOC_TXN_STATUS", 0x80085211 },
}
local SRC_IOCTL = { "REG_SRC_REGISTER", 0x40185200 }

-- ---- the appendix itself ---------------------------------------------

test("the appendix is generated from pkm/uapi/pkm/lcs.h, not written by hand",
    { spec = "PKM *lcs-abi.generated-from-source",
      covered_by = "ci:regenerate-and-diff",
      skip = "a CI property, not a kernel one: pkm/tools/gen-lcs-abi.py " ..
             "rewrites §5.A wholesale from pkm/uapi/pkm/lcs.h — measuring " ..
             "ioctl encodings and struct layouts by compiling a probe " ..
             "against the real header — and `python3 pkm/tools/gen-lcs-abi.py " ..
             "--check` exits non-zero when the committed appendix differs " ..
             "from a fresh run; nothing inside a VM can observe how a " ..
             "document was produced" },
    function(t) end)

-- ---- syscalls and ioctls ---------------------------------------------

test("the three syscall numbers are registered and the neighbouring ones are not",
    { spec = "PKM *lcs-abi.syscall-numbers" }, function(t)
        local w = vm:spawn_worker()
        -- 1102 takes no arguments and answers with a transaction fd.
        local txn = lcs.begin_transaction(w)
        t:assert(txn, "1102 is reg_begin_transaction(void)")
        sys.close(w, txn)
        -- 1100 is reg_open_key(parent_fd, path, desired_access, flags):
        -- the path is the second argument, and it is read.
        local src = machine()
        local open_r = lcs.open_key(src, w, -1, "Machine\\Software\\Test",
            lcs.KEY_ALL_ACCESS)
        t:assert(open_r.ret >= 0,
            "1100 is reg_open_key and reads its path from the second argument: "
                .. sys.errname(open_r.errno or 0))
        sys.close(w, open_r.ret)
        -- 1101 is reg_create_key(const struct reg_create_key_args *): one
        -- pointer argument, and nothing else is consulted.
        local created = lcs.create_key(src, w, { path = "Machine\\Software\\Made" })
        t:assert(created.ret >= 0,
            "1101 is reg_create_key and takes one args pointer: "
                .. sys.errname(created.errno or 0))
        sys.close(w, created.ret)
        for _, hole in ipairs({ 1099, 1103, 1104 }) do
            t:assert_eq(w:syscall(hole, 0, 0, 0, 0).errno, sys.E.NOSYS,
                hole .. " is outside the three LCS numbers")
        end
        w:kill(); w:join()
        src:close()
    end)

test("every published ioctl encoding is accepted on its own fd type and nowhere else",
    { spec = "PKM *lcs-abi.ioctl-numbers" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local txn = assert(lcs.begin_transaction(w))
            local dev = sys.open(w, lcs.DEVICE, sys.O.RDWR | O_NONBLOCK)
            t:assert(dev, "a source device fd opens")

            for _, io in ipairs(KEY_IOCTLS) do
                local r = raw_ioctl(src, w, key, io[2], ioc_size(io[2]))
                t:assert_neq(r.errno, sys.E.NOTTY,
                    io[1] .. " (" .. string.format("0x%08X", io[2])
                        .. ") is a key-fd ioctl")
            end
            for _, io in ipairs(TXN_IOCTLS) do
                local r = raw_ioctl(nil, w, txn, io[2], ioc_size(io[2]))
                t:assert_neq(r.errno, sys.E.NOTTY,
                    io[1] .. " (" .. string.format("0x%08X", io[2])
                        .. ") is a transaction-fd ioctl")
            end
            local reg = raw_ioctl(nil, w, dev, SRC_IOCTL[2], ioc_size(SRC_IOCTL[2]))
            t:assert_neq(reg.errno, sys.E.NOTTY,
                SRC_IOCTL[1] .. " is a source-device ioctl")

            -- Number 0 on the source device and number 0 on a key fd do
            -- not collide: the kernel dispatches on the fd's
            -- file_operations, not globally.
            t:assert_eq(raw_ioctl(nil, w, key, SRC_IOCTL[2],
                ioc_size(SRC_IOCTL[2])).errno, sys.E.NOTTY,
                "REG_SRC_REGISTER, number 0, is not a key-fd ioctl")
            t:assert_eq(raw_ioctl(nil, w, dev, KEY_IOCTLS[1][2],
                ioc_size(KEY_IOCTLS[1][2])).errno, sys.E.NOTTY,
                "REG_IOC_QUERY_VALUE, also number 0, is not a source-device ioctl")
            t:assert_eq(raw_ioctl(nil, w, key, TXN_IOCTLS[1][2], 0).errno,
                sys.E.NOTTY, "REG_IOC_COMMIT is not a key-fd ioctl")
            t:assert_eq(raw_ioctl(nil, w, txn, KEY_IOCTLS[8][2],
                ioc_size(KEY_IOCTLS[8][2])).errno, sys.E.NOTTY,
                "and REG_IOC_QUERY_KEY_INFO is not a transaction-fd ioctl")

            sys.close(w, dev); sys.close(w, txn); sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("each argument size is the size the encoded ioctl declares",
    { spec = "PKM *lcs-abi.argument-sizes" }, function(t)
        -- The `_SIZE` constants are the size field of the encodings, so
        -- the kernel refuses a number that declares one byte more or
        -- one byte less than the published size.
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local all = {}
            for _, io in ipairs(KEY_IOCTLS) do all[#all + 1] = { key, io } end
            local txn = assert(lcs.begin_transaction(w))
            for _, io in ipairs(TXN_IOCTLS) do all[#all + 1] = { txn, io } end
            for _, pair in ipairs(all) do
                local fd, io = pair[1], pair[2]
                local size = ioc_size(io[2])
                local bigger = io[2] + (1 << 16)
                t:assert_eq(raw_ioctl(nil, w, fd, bigger, size + 1).errno,
                    sys.E.NOTTY,
                    io[1] .. " is " .. size .. " bytes, not " .. (size + 1))
                if size > 0 then
                    local smaller = io[2] - (1 << 16)
                    t:assert_eq(raw_ioctl(nil, w, fd, smaller, size - 1).errno,
                        sys.E.NOTTY,
                        io[1] .. " is " .. size .. " bytes, not " .. (size - 1))
                end
            end
            -- REG_CREATE_KEY_ARGS_SIZE is 48: the disposition pointer
            -- lives at offset 40 and is read, which a shorter structure
            -- could not carry.
            local made = lcs.create_key(src, w, { path = "Machine\\Software\\Sized" })
            t:assert(made.ret >= 0, "reg_create_key accepts a 48-byte argument")
            t:assert_eq(made.disposition, lcs.CREATED_NEW,
                "and writes through the pointer at offset 40 of it")
            sys.close(w, made.ret); sys.close(w, txn); sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

-- ---- constant tables -------------------------------------------------

test("the six transaction state codes are the states REG_IOC_TXN_STATUS reports",
    { spec = "PKM *lcs-abi.txn-state-codes" }, function(t)
        local src = machine(function(s)
            s:seed_param("TransactionTimeoutMs", 1000)
            s:key(lcs.LAYERS_PATH)
        end)
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")

            local unbound = assert(lcs.begin_transaction(w))
            t:assert_eq(lcs.txn_status(nil, w, unbound).state, 0,
                "REG_TXN_ACTIVE_UNBOUND is 0")
            lcs.set_value(src, w, key, "A", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = unbound })
            t:assert_eq(lcs.txn_status(nil, w, unbound).state, 1,
                "REG_TXN_ACTIVE_BOUND is 1")
            lcs.commit(src, w, unbound)
            t:assert_eq(lcs.txn_status(nil, w, unbound).state, 2,
                "REG_TXN_COMMITTED is 2")
            sys.close(w, unbound)

            -- An abort while the fd is still open is the layer writer's:
            -- deleting a layer aborts every bound transaction whose log
            -- touches it (§5.3.4).
            local layers = open(t, src, w, lcs.LAYERS_PATH)
            local made = lcs.create_key(src, w,
                { parent_fd = layers, path = "AbortLayer" })
            t:assert(made.ret >= 0, "a layer to write in exists")
            local aborted = assert(lcs.begin_transaction(w))
            t:assert_eq(lcs.set_value(src, w, key, "B", lcs.TYPE.DWORD,
                lcs.dword(1), { layer = "AbortLayer", txn_fd = aborted }).ret, 0,
                "a transaction is bound with a write in that layer")
            t:assert_eq(lcs.delete_key(src, w, made.ret, {}).ret, 0,
                "the layer is deleted under it")
            t:assert_eq(lcs.txn_status(nil, w, aborted).state, 3,
                "REG_TXN_ABORTED is 3")
            sys.close(w, made.ret); sys.close(w, layers)
            sys.close(w, aborted)

            local timed = assert(lcs.begin_transaction(w))
            lcs.set_value(src, w, key, "C", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = timed })
            sys.nanosleep(vm, 2, 0)
            t:assert_eq(lcs.txn_status(nil, w, timed).state, 4,
                "REG_TXN_TIMED_OUT is 4")
            sys.close(w, timed)

            local down = assert(lcs.begin_transaction(w))
            lcs.set_value(src, w, key, "D", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = down })
            src:disconnect()
            t:assert_eq(lcs.txn_status(nil, w, down).state, 5,
                "REG_TXN_SOURCE_DOWN is 5")
            sys.close(w, down)
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the syscall flags and dispositions do what their values say",
    { spec = "PKM *lcs-abi.syscall-flags-and-dispositions" }, function(t)
        local src = machine(function(s)
            s:symlink("Machine\\Software\\Link", "Machine\\Software\\Test")
        end)
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")

            -- REG_OPTION_VOLATILE 0x01, REG_OPTION_CREATE_LINK 0x02.
            local vol = lcs.create_key(src, w,
                { parent_fd = key, path = "Volatile", flags = 0x01 })
            t:assert(vol.ret >= 0, "REG_OPTION_VOLATILE creates: "
                .. sys.errname(vol.errno or 0))
            t:assert(lcs.query_key_info(src, w, vol.ret).volatile,
                "and the key is volatile")
            local link = lcs.create_key(src, w, { parent_fd = key, path = "Made",
                flags = 0x02,
                access = lcs.KEY_ALL_ACCESS | lcs.RIGHT.CREATE_LINK })
            t:assert(link.ret >= 0, "REG_OPTION_CREATE_LINK creates: "
                .. sys.errname(link.errno or 0))
            t:assert(lcs.query_key_info(src, w, link.ret).symlink,
                "and the key is a symlink")

            -- REG_CREATED_NEW 1, REG_OPENED_EXISTING 2.
            t:assert_eq(vol.disposition, 1, "REG_CREATED_NEW is 1")
            local again = lcs.create_key(src, w,
                { parent_fd = key, path = "Volatile" })
            t:assert_eq(again.disposition, 2, "REG_OPENED_EXISTING is 2")

            -- REG_OPEN_LINK 0x01 on reg_open_key: the link itself.
            local followed = open(t, src, w, "Machine\\Software\\Link")
            t:assert_eq(lcs.query_key_info(src, w, followed).name, "Test",
                "without REG_OPEN_LINK the symlink is followed")
            local itself = open(t, src, w, "Machine\\Software\\Link",
                lcs.KEY_ALL_ACCESS, 0x01)
            local info = lcs.query_key_info(src, w, itself)
            t:assert_eq(info.name, "Link", "REG_OPEN_LINK opens the link itself")
            t:assert(info.symlink, "and reports it as a symlink")

            sys.close(w, itself); sys.close(w, followed); sys.close(w, again.ret)
            sys.close(w, link.ret); sys.close(w, vol.ret); sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("each access right gates its own operation and the composites are their unions",
    { spec = "PKM *lcs-abi.key-access-rights" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local full = open(t, src, w, "Machine\\Software\\Test")
            lcs.set_value(src, w, full, "Value", lcs.TYPE.DWORD, lcs.dword(1))

            -- KEY_QUERY_VALUE 0x01 alone queries and does not write.
            local q = open(t, src, w, "Machine\\Software\\Test", 0x00000001)
            t:assert_eq(lcs.query_value(src, w, q, "Value").ret, 0,
                "KEY_QUERY_VALUE (0x01) allows a query")
            t:assert_eq(lcs.set_value(src, w, q, "Value", lcs.TYPE.DWORD,
                lcs.dword(2)).errno, sys.E.ACCES,
                "and not a write: that is KEY_SET_VALUE (0x02)")
            -- KEY_SET_VALUE 0x02 alone writes and does not query.
            local s = open(t, src, w, "Machine\\Software\\Test", 0x00000002)
            t:assert_eq(lcs.set_value(src, w, s, "Value", lcs.TYPE.DWORD,
                lcs.dword(2)).ret, 0, "KEY_SET_VALUE (0x02) allows a write")
            t:assert_eq(lcs.query_value(src, w, s, "Value").errno, sys.E.ACCES,
                "and not a query")
            -- KEY_ENUMERATE_SUB_KEYS 0x08 and READ_CONTROL 0x00020000.
            local e = open(t, src, w, "Machine\\Software\\Test", 0x00000008)
            t:assert_neq(lcs.enum_subkeys(src, w, e, 0).errno, sys.E.ACCES,
                "KEY_ENUMERATE_SUB_KEYS (0x08) allows enumeration")
            local rc = open(t, src, w, "Machine\\Software\\Test", 0x00020000)
            t:assert_eq(lcs.get_security(src, w, rc, lcs.SI.DACL).ret, 0,
                "READ_CONTROL (0x00020000) allows reading the descriptor")

            -- KEY_READ is 0x00020019: query, enumerate, notify, read
            -- control — and not KEY_SET_VALUE.
            local kr = open(t, src, w, "Machine\\Software\\Test", 0x00020019)
            t:assert_eq(lcs.query_value(src, w, kr, "Value").ret, 0,
                "KEY_READ carries KEY_QUERY_VALUE")
            t:assert_eq(lcs.notify(nil, w, kr, lcs.NOTIFY.ALL, false).ret, 0,
                "and KEY_NOTIFY")
            t:assert_eq(lcs.get_security(src, w, kr, lcs.SI.DACL).ret, 0,
                "and READ_CONTROL")
            t:assert_eq(lcs.set_value(src, w, kr, "Value", lcs.TYPE.DWORD,
                lcs.dword(3)).errno, sys.E.ACCES, "and not KEY_SET_VALUE")
            -- KEY_WRITE is 0x00020006: set value and create sub key.
            local kw = open(t, src, w, "Machine\\Software\\Test", 0x00020006)
            t:assert_eq(lcs.set_value(src, w, kw, "Value", lcs.TYPE.DWORD,
                lcs.dword(4)).ret, 0, "KEY_WRITE carries KEY_SET_VALUE")
            local child = lcs.create_key(src, w, { parent_fd = kw, path = "Kid" })
            t:assert(child.ret >= 0, "and KEY_CREATE_SUB_KEY")
            t:assert_eq(lcs.query_value(src, w, kw, "Value").errno, sys.E.ACCES,
                "and not KEY_QUERY_VALUE")

            -- REG_VALID_DESIRED_ACCESS_MASK is 0xF30F003F: a bit outside
            -- it is not a right at all.
            for _, bit in ipairs({ 0x00000040, 0x00000100, 0x00100000,
                                   0x04000000 }) do
                t:assert_eq(lcs.open_key(src, w, -1, "Machine\\Software\\Test",
                    bit).errno, sys.E.INVAL,
                    string.format("0x%08X is outside REG_VALID_DESIRED_ACCESS_MASK",
                        bit))
            end
            t:assert(lcs.open_key(src, w, -1, "Machine\\Software\\Test",
                0x02000000).ret >= 0,
                "while MAXIMUM_ALLOWED (0x02000000) is inside it")

            sys.close(w, child.ret); sys.close(w, kw); sys.close(w, kr)
            sys.close(w, rc); sys.close(w, e); sys.close(w, s); sys.close(w, q)
            sys.close(w, full)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("each security information flag selects its own part of the descriptor",
    { spec = "PKM *lcs-abi.security-information-flags" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local owner = lcs.get_security(src, w, key, 0x1)
            t:assert_eq(owner.ret, 0, "OWNER_SECURITY_INFORMATION (0x01) reads")
            local dacl = lcs.get_security(src, w, key, 0x4)
            t:assert_eq(dacl.ret, 0, "DACL_SECURITY_INFORMATION (0x04) reads")
            t:assert(dacl.sd_len > owner.sd_len,
                "and carries more than the owner alone: " .. dacl.sd_len
                    .. " against " .. owner.sd_len)
            local three = lcs.get_security(src, w, key, 0x1 | 0x2 | 0x4)
            t:assert_eq(three.ret, 0, "the three ordinary flags combine")
            -- SACL_SECURITY_INFORMATION 0x08 is the privileged one.
            t:assert_eq(lcs.get_security(src, w, key, 0x8).errno, sys.E.ACCES,
                "SACL_SECURITY_INFORMATION (0x08) needs ACCESS_SYSTEM_SECURITY")
            -- REG_VALID_SECURITY_INFORMATION is 0x0F exactly.
            t:assert_eq(lcs.get_security(src, w, key, 0x10).errno, sys.E.INVAL,
                "0x10 is outside REG_VALID_SECURITY_INFORMATION (0x0F)")
            t:assert_eq(lcs.get_security(src, w, key, 0x0).errno, sys.E.INVAL,
                "and naming nothing is not a request either")
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the value type codes are the ones a value may carry",
    { spec = "PKM *lcs-abi.value-types" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            -- REG_NONE 0 through REG_QWORD 11, each written and read
            -- back as itself. REG_LINK (6) belongs to a symlink key's
            -- default value and is not writable here.
            local types = { 0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11 }
            for _, code in ipairs(types) do
                local data = code == 4 and lcs.dword(7)
                    or code == 11 and lcs.qword(7) or "payload\0"
                t:assert_eq(lcs.set_value(src, w, key, "T" .. code, code,
                    data).ret, 0, "type " .. code .. " is a value type")
                local back = lcs.query_value(src, w, key, "T" .. code)
                t:assert_eq(back.type, code,
                    "and comes back as " .. code .. ", not something else")
            end
            -- REG_TOMBSTONE is 0xFFFF, a long way past the sequence.
            t:assert_eq(lcs.set_value(src, w, key, "Tomb", 0xFFFF, "").ret, 0,
                "REG_TOMBSTONE (0xFFFF) is the tombstone marker")
            -- 12 is one past REG_QWORD and is not a type.
            t:assert_eq(lcs.set_value(src, w, key, "Bad", 12, "abcd").errno,
                sys.E.INVAL, "12 is one past REG_QWORD and is not a type")
            t:assert_eq(lcs.set_value(src, w, key, "Bad2", 0xFFFE, "abcd").errno,
                sys.E.INVAL, "nor is 0xFFFE, one below REG_TOMBSTONE")
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("each watch filter bit selects exactly its own event types",
    { spec = "PKM *lcs-abi.watch-event-types-and-filters" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            -- One armed watcher per filter, then every kind of change.
            local function types_for(filter)
                local fd = open(t, src, w, "Machine\\Software\\Test")
                t:assert_eq(lcs.notify(nil, w, fd, filter, false).ret, 0,
                    "REG_IOC_NOTIFY accepts filter "
                        .. string.format("0x%02X", filter))
                lcs.set_value(src, w, fd, "W", lcs.TYPE.DWORD, lcs.dword(1))
                lcs.delete_value(src, w, fd, "W", {})
                local child = lcs.create_key(src, w, { parent_fd = fd, path = "WK" })
                if child.ret >= 0 then
                    lcs.delete_key(src, w, child.ret, {})
                    sys.close(w, child.ret)
                end
                lcs.set_security(src, w, fd, lcs.SI.DACL, lcs.permissive_sd())
                local ev = lcs.read_events(nil, w, fd)
                local seen = {}
                for _, e in ipairs(ev.events) do seen[#seen + 1] = e.type end
                sys.close(w, fd)
                return table.concat(seen, ",")
            end
            t:assert_eq(types_for(0x01), "1,2",
                "REG_NOTIFY_VALUE (0x01) is REG_WATCH_VALUE_SET (1) and "
                    .. "REG_WATCH_VALUE_DELETED (2)")
            t:assert_eq(types_for(0x02), "3,4",
                "REG_NOTIFY_SUBKEY (0x02) is REG_WATCH_SUBKEY_CREATED (3) and "
                    .. "REG_WATCH_SUBKEY_DELETED (4)")
            t:assert_eq(types_for(0x04), "5",
                "REG_NOTIFY_SD (0x04) is REG_WATCH_SD_CHANGED (5)")
            t:assert_eq(types_for(0x07), "1,2,3,4,5",
                "and REG_NOTIFY_ALL (0x07) is the union of the three")
            t:assert_eq(lcs.notify(nil, w, open(t, src, w,
                "Machine\\Software\\Test"), 0x08, false).errno, sys.E.INVAL,
                "0x08 is outside REG_NOTIFY_ALL and is not a filter")

            -- REG_WATCH_KEY_DELETED (6) reaches a watcher whose key goes.
            local doomed = lcs.create_key(src, w,
                { path = "Machine\\Software\\Doomed" })
            t:assert(doomed.ret >= 0, "a key to delete is created")
            lcs.notify(nil, w, doomed.ret, lcs.NOTIFY.ALL, false)
            lcs.delete_key(src, w, doomed.ret, {})
            local ev = lcs.read_events(nil, w, doomed.ret)
            local last = ev.events[#ev.events]
            t:assert(last and last.type == 6,
                "REG_WATCH_KEY_DELETED is 6")
            sys.close(w, doomed.ret)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("a watch record is laid out at the published offsets",
    { spec = "PKM *lcs-abi.watch-record-layout" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            t:assert_eq(lcs.notify(nil, w, key, lcs.NOTIFY.VALUE, false).ret, 0,
                "a plain watcher is armed")
            lcs.set_value(src, w, key, "Named", lcs.TYPE.DWORD, lcs.dword(1))
            local raw = lcs.read_events(nil, w, key)
            t:assert(raw.ret > 0, "a record is readable")
            local buf = raw.out_bufs[1]:sub(1, raw.ret)
            -- REG_WATCH_EVENT_TOTAL_LEN_OFFSET 0, _TYPE_OFFSET 4,
            -- _NAME_LEN_OFFSET 6, _NAME_OFFSET 8, _MIN_SIZE 8.
            local total = string.unpack("<I4", buf, 1)
            t:assert_eq(total, raw.ret,
                "total_len is a u32 at offset 0 and spans the record")
            t:assert_eq(string.unpack("<I2", buf, 5), 1,
                "type is a u16 at offset 4 and is REG_WATCH_VALUE_SET")
            local name_len = string.unpack("<I2", buf, 7)
            t:assert_eq(name_len, #"Named",
                "name_len is a u16 at offset 6")
            t:assert_eq(buf:sub(9, 8 + name_len), "Named",
                "and the name begins at offset 8, REG_WATCH_EVENT_MIN_SIZE")
            sys.close(w, key)

            -- A subtree watcher's record carries the path after the
            -- name: depth u16 at the relative offset 0, then
            -- (len u16, bytes) components from relative offset 2.
            local root = open(t, src, w, "Machine")
            t:assert_eq(lcs.notify(nil, w, root, lcs.NOTIFY.VALUE, true).ret, 0,
                "a subtree watcher is armed on the hive root")
            local deep = open(t, src, w, "Machine\\Software\\Test")
            lcs.set_value(src, w, deep, "Sub", lcs.TYPE.DWORD, lcs.dword(1))
            local sub = lcs.read_events(nil, w, root)
            t:assert(sub.ret > 0, "and its record is readable")
            local sbuf = sub.out_bufs[1]:sub(1, sub.ret)
            local slen = string.unpack("<I2", sbuf, 7)
            local at = 9 + slen
            local depth = string.unpack("<I2", sbuf, at)
            t:assert_eq(depth, 2,
                "the relative path depth is a u16 straight after the name")
            at = at + 2
            local first_len = string.unpack("<I2", sbuf, at)
            t:assert_eq(sbuf:sub(at + 2, at + 1 + first_len), "Software",
                "and each component is a u16 length and its bytes")
            sys.close(w, deep); sys.close(w, root)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

-- ---- the RSI wire ----------------------------------------------------

test("an RSI request and response are laid out at the published offsets",
    { spec = "PKM *lcs-abi.rsi-wire-layout" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local mark = src:mark()
            lcs.query_value(src, w, key, "Nothing")
            local req = src:served(lcs.OP.QUERY_VALUES, mark)[1]
            t:assert(req, "the source was asked for the values")
            local raw = req.raw
            t:assert_eq(string.unpack("<I4", raw, 1), #raw,
                "RSI_REQUEST_TOTAL_LEN_OFFSET is 0 and spans the frame")
            t:assert_eq(string.unpack("<I8", raw, 5), req.id,
                "RSI_REQUEST_ID_OFFSET is 4")
            t:assert_eq(string.unpack("<I2", raw, 13), 0x0020,
                "RSI_REQUEST_OP_CODE_OFFSET is 12")
            t:assert_eq(string.unpack("<I8", raw, 15), 0,
                "RSI_REQUEST_TXN_ID_OFFSET is 14")
            t:assert_eq(#raw - #req.payload, 22,
                "and RSI_REQUEST_HEADER_SIZE is 22")
            t:assert_eq(raw:sub(23, 38), src:lookup("Machine\\Software\\Test"),
                "so the payload begins with the 16-byte GUID: RSI_GUID_SIZE")

            -- The response the source writes carries the op with
            -- RSI_RESPONSE_BIT set, a 14-byte header and a u32 status
            -- at RSI_RESPONSE_STATUS_OFFSET; without the bit set the
            -- kernel does not match it to the request.
            local frame = lcs.response_frame(1, lcs.OP.QUERY_VALUES,
                lcs.STATUS.OK, "")
            t:assert_eq(#frame, 18, "RSI_MIN_RESPONSE_SIZE is 18")
            t:assert_eq(string.unpack("<I2", frame, 13),
                lcs.OP.QUERY_VALUES | 0x8000,
                "RSI_RESPONSE_BIT is 0x8000 and rides in the op at offset 12")
            t:assert_eq(string.unpack("<I4", frame, 15), lcs.STATUS.OK,
                "and RSI_RESPONSE_STATUS_OFFSET is 14, RSI_STATUS_SIZE 4")

            local mark2 = src:mark()
            src:intercept(lcs.OP.QUERY_VALUES, function(_, r)
                -- The same frame with the response bit cleared.
                return string.pack("<I4I8I2I4", 18, r.id, r.op, lcs.STATUS.OK)
            end)
            local bad = lcs.query_value(src, w, key, "Nothing")
            src:intercept(lcs.OP.QUERY_VALUES, nil)
            t:assert(bad.ret < 0,
                "a response without RSI_RESPONSE_BIT is not the answer to the request")
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the RSI op codes are the numbers on the wire",
    { spec = "PKM *lcs-abi.rsi-op-codes" }, function(t)
        local src = machine(function(s) s:key(lcs.LAYERS_PATH) end)
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local layers = open(t, src, w, lcs.LAYERS_PATH)
            local mark = src:mark()
            -- A battery wide enough to put every verb on the wire.
            local extra = lcs.create_key(src, w, { parent_fd = layers, path = "Extra" })
            lcs.set_value(src, w, key, "V", lcs.TYPE.DWORD, lcs.dword(1))
            lcs.query_value(src, w, key, "V")
            lcs.enum_subkeys(src, w, key, 0)
            lcs.delete_value(src, w, key, "V", {})
            lcs.blanket_tombstone(src, w, key, "base", true)
            local child = lcs.create_key(src, w, { parent_fd = key, path = "Child" })
            lcs.hide_key(src, w, child.ret, { layer = "Extra" })
            lcs.set_security(src, w, key, lcs.SI.DACL, lcs.permissive_sd())
            lcs.flush(src, w, key)
            local txn = assert(lcs.begin_transaction(w))
            lcs.set_value(src, w, key, "T", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = txn })
            lcs.commit(src, w, txn)
            sys.close(w, txn)
            local aborted = assert(lcs.begin_transaction(w))
            lcs.set_value(src, w, key, "U", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = aborted })
            sys.close(w, aborted)
            src:pump()
            lcs.delete_key(src, w, child.ret, {})
            lcs.delete_key(src, w, extra.ret, {})
            src:pump()

            local seen = {}
            for i = mark, #src.log do seen[src.log[i].op] = true end
            local documented = {
                [0x0001] = "RSI_LOOKUP", [0x0002] = "RSI_CREATE_ENTRY",
                [0x0003] = "RSI_HIDE_ENTRY", [0x0004] = "RSI_DELETE_ENTRY",
                [0x0005] = "RSI_ENUM_CHILDREN", [0x0010] = "RSI_CREATE_KEY",
                [0x0011] = "RSI_READ_KEY", [0x0012] = "RSI_WRITE_KEY",
                [0x0013] = "RSI_DROP_KEY", [0x0020] = "RSI_QUERY_VALUES",
                [0x0021] = "RSI_SET_VALUE", [0x0022] = "RSI_DELETE_VALUE_ENTRY",
                [0x0023] = "RSI_SET_BLANKET_TOMBSTONE",
                [0x0030] = "RSI_BEGIN_TRANSACTION",
                [0x0031] = "RSI_COMMIT_TRANSACTION",
                [0x0032] = "RSI_ABORT_TRANSACTION", [0x0040] = "RSI_FLUSH",
                [0x0050] = "RSI_DELETE_LAYER",
            }
            for op in pairs(seen) do
                t:assert(documented[op],
                    string.format("0x%04X is one of the published op codes", op))
            end
            for _, op in ipairs({ 0x0001, 0x0002, 0x0003, 0x0004, 0x0005,
                                  0x0010, 0x0011, 0x0012, 0x0020, 0x0021,
                                  0x0022, 0x0023, 0x0030, 0x0031, 0x0032,
                                  0x0040, 0x0050 }) do
                t:assert(seen[op], documented[op] .. " is "
                    .. string.format("0x%04X", op) .. " on the wire")
            end
            sys.close(w, child.ret); sys.close(w, extra.ret)
            sys.close(w, layers); sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("each RSI status code maps to the errno the caller sees",
    { spec = "PKM *lcs-abi.rsi-status-codes" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local cases = {
                { 1, "RSI_NOT_FOUND", sys.E.NOENT },
                { 2, "RSI_ALREADY_EXISTS", sys.E.EXIST },
                { 3, "RSI_STORAGE_ERROR", sys.E.IO },
                { 4, "RSI_NOT_EMPTY", sys.E.NOTEMPTY },
                { 5, "RSI_TOO_LARGE", sys.E.NOSPC },
                { 6, "RSI_TXN_BUSY", sys.E.BUSY },
                { 7, "RSI_INVALID", sys.E.INVAL },
                { 8, "RSI_CAS_FAILED", sys.E.AGAIN },
                { 9, "RSI_TXN_NOT_SUPPORTED", sys.E.OPNOTSUPP },
            }
            for _, c in ipairs(cases) do
                src:intercept(lcs.OP.QUERY_VALUES, function() return c[1], "" end)
                local r = lcs.query_value(src, w, key, "Anything")
                src:intercept(lcs.OP.QUERY_VALUES, nil)
                t:assert_eq(r.errno, c[3],
                    c[2] .. " (" .. c[1] .. ") is " .. sys.errname(c[3]))
            end
            -- RSI_OK is 0 and is not a failure at all.
            local fine = lcs.query_value(src, w, key, "Anything")
            t:assert_eq(fine.errno, sys.E.NOENT,
                "RSI_OK (0) is success, and the absent value is the caller's ENOENT")
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("a status outside the published set is not a status",
    { spec = "PKM *lcs-abi.rsi-status-codes" }, function(t)
        -- Ten is one past RSI_TXN_NOT_SUPPORTED. A source that answers
        -- with it has desynchronised, which is not an error the caller
        -- is told about in the status's own terms.
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            src:intercept(lcs.OP.QUERY_VALUES, function(_, req)
                return string.pack("<I4I8I2I4", 18, req.id,
                    req.op | lcs.RESPONSE_BIT, 10)
            end)
            local r = lcs.query_value(src, w, key, "Anything")
            src:intercept(lcs.OP.QUERY_VALUES, nil)
            t:assert(r.ret < 0,
                "the call fails rather than being given an unknown status: "
                    .. sys.errname(r.errno or 0))
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the two path target types tell a GUID entry from a HIDDEN one",
    { spec = "PKM *lcs-abi.rsi-path-target-types" }, function(t)
        -- A path entry answers RSI_LOOKUP either with a key GUID
        -- (RSI_PATH_TARGET_GUID, 0) or with the fact that the name is
        -- masked in that layer (RSI_PATH_TARGET_HIDDEN, 1).
        local src = machine(function(s)
            s:seed_layer("Over", { precedence = 10, enabled = 1 })
            local sw = s:lookup("Machine\\Software")
            s:hide(sw, "Test", "Over")
            s:key("Machine\\Software\\Visible")
        end)
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local visible = lcs.open_key(src, w, -1, "Machine\\Software\\Visible",
                lcs.RIGHT.KEY_READ)
            t:assert(visible.ret >= 0,
                "target type 0 names a key GUID and the key resolves: "
                    .. sys.errname(visible.errno or 0))
            local hidden = lcs.open_key(src, w, -1, "Machine\\Software\\Test",
                lcs.RIGHT.KEY_READ)
            t:assert_eq(hidden.errno, sys.E.NOENT,
                "target type 1 masks the name and the key does not")
            if visible.ret >= 0 then sys.close(w, visible.ret) end
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the RSI_WRITE_KEY field mask names the fields the request carries",
    { spec = "PKM *lcs-abi.rsi-write-key-field-mask" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local mark = src:mark()
            lcs.set_security(src, w, key, lcs.SI.DACL, lcs.permissive_sd())
            local sd_writes = src:served(lcs.OP.WRITE_KEY, mark)
            t:assert(#sd_writes > 0, "a descriptor change writes the key record")
            local mask = string.unpack("<I4", sd_writes[1].payload, 17)
            t:assert_eq(mask & 0x01, 0x01,
                "RSI_WRITE_KEY_FIELD_SD (0x01) is set when the descriptor changes")

            mark = src:mark()
            lcs.set_value(src, w, key, "Stamped", lcs.TYPE.DWORD, lcs.dword(1))
            local stamp = src:served(lcs.OP.WRITE_KEY, mark)
            t:assert(#stamp > 0, "a value write stamps the key's last write time")
            local tmask = string.unpack("<I4", stamp[1].payload, 17)
            t:assert_eq(tmask & 0x02, 0x02,
                "RSI_WRITE_KEY_FIELD_LAST_WRITE_TIME (0x02) is set for it")
            t:assert_eq(tmask & ~0x03, 0,
                "and nothing outside RSI_WRITE_KEY_FIELD_KNOWN_MASK (0x03) is ever set")
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)

test("the transaction modes and the private-hive registration flag",
    { spec = "PKM *lcs-abi.rsi-txn-modes-and-registration-flags" }, function(t)
        local src = machine()
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local key = open(t, src, w, "Machine\\Software\\Test")
            local mark = src:mark()
            local txn = assert(lcs.begin_transaction(w))
            lcs.set_value(src, w, key, "RW", lcs.TYPE.DWORD, lcs.dword(1),
                { txn_fd = txn })
            local begun = src:served(lcs.OP.BEGIN_TXN, mark)
            t:assert(#begun > 0, "binding a transaction begins one at the source")
            t:assert_eq(string.unpack("<I4", begun[1].payload, 9), 0,
                "RSI_TXN_READ_WRITE is 0")
            lcs.commit(src, w, txn)
            sys.close(w, txn)

            -- A backup snapshot is the read-only mode.
            local rd, wr = sys.pipe(w)
            local root = open(t, src, w, "Machine")
            mark = src:mark()
            lcs.backup(src, w, root, wr)
            local ro = src:served(lcs.OP.BEGIN_TXN, mark)
            t:assert(#ro > 0, "a backup begins a transaction of its own")
            t:assert_eq(string.unpack("<I4", ro[1].payload, 9), 1,
                "RSI_TXN_READ_ONLY is 1")
            sys.close(w, wr); sys.close(w, rd); sys.close(w, root)
            sys.close(w, key)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end

        -- RSI_HIVE_PRIVATE is 0x01 in reg_src_hive_entry.flags: the hive
        -- is reachable only through a token carrying its scope GUID.
        local scope = lcs.guid()
        local private = lcs.source(vm, { hives = {
            { name = "Scoped", flags = 0x01, scope = scope } } })
        private:key("Scoped\\Thing")
        assert(private:register())
        private:pump()
        local w2 = vm:spawn_worker()
        local r = lcs.open_key(private, w2, -1, "Scoped\\Thing", lcs.RIGHT.KEY_READ)
        t:assert_eq(r.errno, sys.E.NOENT,
            "flags 0x01 marks the hive private: a scopeless caller does not see it")
        w2:kill(); w2:join()
        private:close()
    end)

-- ---- the backup stream -----------------------------------------------

test("the backup record types and magic are what the stream carries",
    { spec = "PKM *lcs-abi.backup-record-types" }, function(t)
        -- A hive holding one of everything the stream can carry: a
        -- layer (base is always written first), keys, path entries, a
        -- value and a blanket tombstone.
        local src = machine(function(s)
            local k = s:key("Machine\\Software\\Test")
            s:value(k, "Plain", lcs.TYPE.DWORD, lcs.dword(1))
            s:blanket(k, "base")
        end)
        local w = vm:spawn_worker()
        local ok, err = pcall(function()
            local root = open(t, src, w, "Machine")
            local rd, wr = sys.pipe(w)
            local b = lcs.backup(src, w, root, wr)
            t:assert_eq(b.ret, 0, "a backup is taken: " .. sys.errname(b.errno or 0))
            sys.close(w, wr)
            local chunks = {}
            while true do
                local d = sys.read(w, rd, 65536)
                if not d or #d == 0 then break end
                chunks[#chunks + 1] = d
            end
            sys.close(w, rd)
            local stream = table.concat(chunks)
            t:assert(#stream > 0, "and the stream is readable")

            local documented = {
                [0x01] = "REG_BACKUP_HEADER", [0x02] = "REG_BACKUP_LAYER",
                [0x03] = "REG_BACKUP_KEY", [0x04] = "REG_BACKUP_PATH_ENTRY",
                [0x05] = "REG_BACKUP_VALUE",
                [0x06] = "REG_BACKUP_BLANKET_TOMBSTONE",
                [0xFF] = "REG_BACKUP_TRAILER",
            }
            local at, seen, last = 1, {}, nil
            while at + 6 <= #stream + 1 do
                local rtype, rlen = string.unpack("<I2I4", stream, at)
                t:assert(documented[rtype],
                    string.format("record type 0x%02X is a published one", rtype))
                seen[rtype] = true
                last = rtype
                at = at + rlen
            end
            t:assert_eq(string.unpack("<I2", stream, 1), 0x01,
                "REG_BACKUP_HEADER (0x01) is the first record")
            t:assert_eq(last, 0xFF, "REG_BACKUP_TRAILER (0xFF) is the last")
            for _, code in ipairs({ 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0xFF }) do
                t:assert(seen[code],
                    documented[code] .. " appears in a stream that has one")
            end
            sys.close(w, root)
        end)
        w:kill(); w:join()
        src:close()
        if not ok then error(err, 0) end
    end)
